name: .NET Core

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: AmazonAuthSignatureV4
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.100' # SDK Version to use.
    - name: Build AmazonAuthSignatureV4
      run: dotnet build      
      run: dotnet test

