name: .NET Core

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: AmazonAuthSignatureV4
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.100' # SDK Version to use.
    - name: Build AmazonAuthSignatureV4      
      run: dotnet build
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: AmazonAuthSignatureV4
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.100' # SDK Version to use.
    - name: Build AmazonAuthSignatureV4      
      run: dotnet test
#  publish:
#    name: list on nuget
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2

      # Required for a specific dotnet version that doesn't come with ubuntu-latest / windows-latest
      # Visit bit.ly/2synnZl to see the list of SDKs that are pre-installed with ubuntu-latest / windows-latest
      #- name: Setup dotnet
      #  uses: actions/setup-dotnet@v1
      #  with:
      #    dotnet-version: 3.1.100
      
      # Publish
      #- name: publish on version change
      #  uses: rohith/publish-nuget@v2.1.1
      #  with:
      #    PROJECT_FILE_PATH: AWS.AmazonAuthSignatureV4/AWS.AmazonAuthSignatureV4.csproj # Relative to repository root
          # VERSION_FILE_PATH: Directory.Build.props # Filepath with version info, relative to repository root. Defaults to project file
          # VERSION_REGEX: <Version>(.*)<\/Version> # Regex pattern to extract version info in a capturing group
          # TAG_COMMIT: true # Flag to enable / disalge git tagging
          # TAG_FORMAT: v* # Format of the git tag, [*] gets replaced with version
          # NUGET_KEY: ${{secrets.NUGET_API_KEY}} # nuget.org API key (oy2dxhe6yxk4k4ntajuqt3bf6kqrty4unjww4v6e6uofue)
          # PACKAGE_NAME: NuGet package name, required when it's different from project name. Defaults to project name
